### PR TITLE
Changed `jdk` to scalar instead of array

### PR DESCRIPTION
**Pull request by cotsog**
This should fix your Travis CI build. :)

### CODE REVIEW

**Comment by Wekra** [comment]
Thank you very much @cotsog! The build is running again so now I can concentrate on how to get rid of the invoked ant command 😬

**Comment by cotsog** [comment]
@Wekra I can help with that as well! The `ant` command is our default `script:` step for Java builds. See https://docs.travis-ci.com/user/languages/java/.

All you need to do is to override it with your own command in your .travis.yml file e.g.

```yaml
script: <YOUR OWN COMMAND>
```

If you don't need this step, you can also set it to `skip` e.g.

```yaml
script: skip
```

Hope this helps!

**Comment by Wekra** [comment]
```yml
 addons:
        apt:
          # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
          sources:
            - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
          packages:
            - libstdc++6
            - fonts-droid
          before_script:
            - sudo apt-get update
            - sudo apt-get install unzip
            - wget https://services.gradle.org/distributions/gradle-3.5-bin.zip
            - unzip gradle-3.5-bin.zip
            - export GRADLE_HOME=$PWD/gradle-3.5
            - export PATH=$GRADLE_HOME/bin:$PATH
            - git clone https://github.com/flutter/flutter.git -b beta
            - export PATH=./flutter/bin:$PATH
          script:
            - ./flutter/bin/flutter -v build apk
```
@cotsog So looking at the snippet above - it seems that I've been putting the `before_script` and `script` parts wrongly nested below `addons`, right?

**Comment by cotsog** [comment]
@Wekra right, these keys need to be at the same level as the `addons` key i.e.

```yaml
before_script:
  - sudo apt-get update
  - sudo apt-get install unzip
  - wget https://services.gradle.org/distributions/gradle-3.5-bin.zip
  - unzip gradle-3.5-bin.zip
  - export GRADLE_HOME=$PWD/gradle-3.5
  - export PATH=$GRADLE_HOME/bin:$PATH
  - git clone https://github.com/flutter/flutter.git -b beta
  - export PATH=./flutter/bin:$PATH
script:
  - ./flutter/bin/flutter -v build apk
addons:
  apt:
  # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - libstdc++6
      - fonts-droid
```

**Comment by Wekra** [comment]
Great, it finally works! Thank you so much @cotsog!

**Comment by cotsog** [comment]
Pleasure! And happy building!

**Pull request merged**
